version: '3'

services:
  database:
    image: postgres:12-alpine
    environment:
        - DB_POSTGRES=true
        - PGPORT=5432
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - shared-network
    volumes:
      - database-volume:/var/lib/postgresql/data
    restart: on-failure

  api:
    build: ./api
    ports:
      - '${APP_PORT}:3000'
    environment:
      - NODE_CONFIG={"host":"${HOST}", "port":${APP_PORT}, "authentication":{ "oauth":{ "redirect":"http://${HOST}:${NGINX_PORT}/login?", "github":{"redirect_uri":"http://${HOST}:${NGINX_PORT}/api/oauth/github/callback","key":"${GITHUB_KEY}","secret":"${GITHUB_SECRET}"}, "google":{"redirect_uri":"http://${HOST}:${NGINX_PORT}/api/oauth/google/callback","key":"${GOOGLE_KEY}","secret":"${GOOGLE_SECRET}"}}},"postgresql":{"client":"pg","connection":"postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"}}
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - shared-network
    depends_on:
      - database
    command: yarn run dev -L

  nginx:
    image: nginx:alpine
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - "./client/public:/usr/src/api/public"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - shared-network
    depends_on:
      - api

volumes:
  api:
  database-volume:

networks:
  shared-network:
